title: "ENGL 253: Topics in Literature and New Media<br />Writing with Robots"
author: Ryan Cordell
url: https://s24wwr.ryancordell.org # root address of the site
description: > # description of the site (multiple lines allowed) 
  <p style="float: left; padding: 10px 10px 10px 10px;"><img src="/images/robotauthor.png" width="300" alt="Robotauthor, our class mascot" ”></p>
  <p>UIUC, Spring 2023<br />
  Instructor: <a href="mailto:rcordell@illinois.edu">Ryan Cordell</a></p>
  <p>In 2024, it can feel like Artificial Intelligence is all anyone is talking about, from the university to the news to our social media feeds. The release of ChatGPT in particular has sparked fears about how students will use or abuse AI writing tools in classes, and how professionals should apply these same tools in their work. "Writing with Robots" addresses these controversies directly, first by introducing students to the long history of humans seeking to automate—or at least simulate—intelligence and creativity. We will study historical automata and automated writing technologies, discussing how technology and writing have mutually influenced each other over centuries, and how artists and writers have by turns adopted, adapted, and resisted such technologies. We will read speculative fiction that probes the boundaries of human, non-human, and mechanical intelligence, considering how such literature might inform current debates. Finally, we will learn about and experiment with contemporary AI tools, seeking to understand their affordances and limitations and to construct a framework for productive, creative, and ethical engagements with this newest medium of automated writing.</p>

permalink: /:slug

favicon: "./logo.png" # relative path to site's favicon

twitter:
    username: # update or delete this
    card: summary_large_image

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  back_home_text: "home.." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer
  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: true # show blog posts added in _posts
  show_old_projects: true # show old projects as cards, add in _data/home.yml
  show_misc_list: true # show generic vertical list for misc details, add _data/home.yml
  show_reading_time: true # show number of words and reading time in the blog posts
  show_tags: false # show tags in a blog posts
  # options for "home" page
  home:
    title_projects: Modules
    title_misc_list: Course Details
    title_blog: Updates
    title_old_projects: Useful Links

soopr:
  publish_token: "" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
